name = "diary"
save = "Save"
add-midia = "Add midia"
write-about-day = "Write about your day! :D"
happy = "Happy"
peace = "Peace"
sad = "Sad"
confused = "Confused"
shame = "Shame"
angry = "Angry"
meh = "Meh"
tired = "Tired"
how-did-you-felt = "How did you felt?"
write-day-hint = "Write about your day here.."
write = "Write"
read = "Read"
explore = "Explore"
about = "About"
warning = "Warning"
finish-text = """
Finish writing about your day!

And dont forget to select the emotion of the day."""
text-style-tip = ""
"" = ""
