name = "diário"
save = "Salvar"
add-midia = "Adicionar mídia"
write-about-day = "Escreva sobre o seu dia! :D"
happy = "Feliz"
peace = "Paz"
sad = "Triste"
confused = "Confuso"
shame = "Vergonha"
angry = "Bravo"
meh = "Meh"
tired = "Cansado"
how-did-you-felt = "Como você se sentiu hoje?"
write-day-hint = "Escreva sobre seu dia aqui..."
write = "Escreva"
read = "Leia"
explore = "Navegue"
about = "Sobre"
warning = "Atenção"
finish-text = """
Termine de escrever sobre o seu dia!

E não esqueça de escolher a emoção do dia"""
